### PR TITLE
Splitting into services and locators and adding ioc registration

### PR DESCRIPTION
**Pull request by wwwlicious**
Using #31 reference architecture have split into services
Resolved issue #26

### CODE REVIEW

**Comment by wwwlicious** [comment]
sorry that this is my master branch and not a feature branch, I get it right soon hopefully!

**Comment by kevinkuszyk** [comment]
Looks good.  Let me know when you're done and I'll merge it.  I have a couple of small comments which I'll post onto the code.

To answer your points above:

> sorry that this is my master branch and not a feature branch, I'll get it right soon hopefully!

Don't worry - opening pull requests from a branch just makes it easier to sync up your fork with the upstream repro.  Also it means you can open more than one pull request at a time and keep them focused on a specific issue.

> the generator is responsible for creating the syntaxtree but does not write it out, I left that to the compilermodule as I thought it might be easier for testing 

Agreed, I think this is the correct approach.

> I left out the ControllerLocator for now to avoid refactoring the ControllerRewriter

No problem - we can fix that up later.

**Comment by wwwlicious** [comment]
It should be ok to merge, only thing I've noticed is that the DI constructor injection wasn't happening for IEnumerable types so I might revert that change once I check some more.

**Comment by kevinkuszyk** [comment]
If you can push those two changes, I'll merge it in.

**Pull request merged**
