### PR TITLE
Adding views to generated file

### PR DESCRIPTION
**Pull request by wwwlicious**
Created an IViewLocator interface and default implementation for discovery of project razor view files
Re-added IServiceProvider into CompilerModule ctor.

### CODE REVIEW

**Comment by kevinkuszyk** [comment]
I've merged the first two commits.

Can you make a branch for the plugin experiment and we can discuss it there?

**Comment by wwwlicious** [comment]
Sure, think I've done something silly with git though as it says the PR has conflicts as I thought it would just ignore the two commits you merged.

**Comment by kevinkuszyk** [comment]
That might have been me me when I merged it.  Are you able to pull the latest changes into your master branch?

**Comment by wwwlicious** [comment]
when I did 'git pull master' it told me there was nothing to update. Think I'm still 'a bit dangerous' when it comes to git, sorry! :)

**Comment by kevinkuszyk** [comment]
Don't worry - I'm by no means an expert.  I think these are the commands you need to sync up with the parent repro:

````
git fetch upstream
git checkout master
git merge upstream/master
````

If I have made changes to my `master` branch, I usually rebase it instead of merging:

````
git rebase upstream/master
````

More info on syncing a fork [here](https://help.github.com/articles/syncing-a-fork/).

**Pull request closed without merging**
