### PR TITLE
Reference architecture

### PR DESCRIPTION
**Pull request by kevinkuszyk**
@wwwlicious - these are my initial thoughts on architecture.

My thinking is that `R4MvcPreCompileModule` is the composition root.  All the work is done from the `R4MvcGenerator` which is created along with it's dependencies by the IoC container.  The key aspects are:
1. We have services for each of the major pieces of work, `IControllerLocatorService`, `IControllerGeneratorService`, `IControllerRewriterService` etc.
2. We have interfaces and default implementations for `IControllerLocator`, `IViewLocator` and `IStaticFileLocator`.
3. As you suggested, the `R4MvcCompiler` in the host app derives from our `R4MvcPreCompileModule`.  
4. There is a hook in the `R4MvcCompiler` to replace or add to our default locators.

I'm still unsure about the shape of our extensiblity API, and as you identified in #30 I'm not sure how the DI will work.

Thoughts?

### CODE REVIEW

**Comment by wwwlicious** [comment]
Looks good, I still can't see how to register objects into IServiceProvider though so it would be good to resolve that issue asap.

One question on the design, what are the effects of exposing roslyn classes in extensibility mechanisms? 
should we concern ourselves that target projects will need to take dependencies on it and that users writing overrides will need to understand how to mess with syntax trees as from recent experience, it's no picnic!

**Comment by wwwlicious** [comment]
on DI, if the IServiceProvider is not possible, we could do one or more of the following:

* take a dependency on an external Ioc library (prob least desirable)
* provider a hook, or reuse the aspnet vnext hooks for injecting host app's preferred Ioc
* grab something small and lightweight like funq and internalise it (servicestack did this to good effect)

Agree that using IServiceProvider is the preferable choice though, just can't figure it out at the moment.

One thing I haven't wrapped my head around is any possible issues with Ioc in compile time vs runtime. For compilation we require the locators etc, for runtime we require virtualpathprovider and modelunbinder instances? 
The compilemodule I assume is not initialised in runtime (haven't checked this but it would make sense) so...?

**Comment by wwwlicious** [comment]
I think i've figured out how to setup IServiceProvider but I've come up against an issue with the design I'm not sure how best to approach. First, we can update/replace the IServiceProvider like so:

````csharp
public static class IocConfig
{
  public static IServiceProvider RegisterServices(IServiceProvider serviceProvider, IEnumerable<IViewLocator> viewLocators, IEnumerable<IStaticFileLocator> staticFileLocators)
  {
    var appBuilder = new ApplicationBuilder(serviceProvider);

    // register types for IServiceProvider here
    appBuilder.UseServices(
      svc =>
	{
	  svc.AddInstance(typeof(IEnumerable<IViewLocator>), viewLocators);
	  svc.AddTransient<IViewLocatorService>();
	});
	return appBuilder.ApplicationServices;
	}
}
````

Next if we have the following ViewLocatorService and DefaultRazorViewLocator

```` csharp
public class ViewLocatorService : IViewLocatorService
{
  private readonly IEnumerable<IViewLocator> _viewLocators;

  public ViewLocatorService(IEnumerable<IViewLocator> viewLocators)
  {
    _viewLocators = viewLocators;
  }

  public IEnumerable<View> FindViews()
  {
    return _viewLocators.SelectMany(x => x.Find());
  }
}

public class DefaultRazorViewLocator : IViewLocator
{
  private readonly Project _project;
  private const string _extension = ".cshtml";
  
  public DefaultRazorViewLocator()
  {
    // Project is not available in CompilerModule when this instance is created
  }

  public View[] Find()
  {
    // how to have Project available here to get ContentFiles without changing interface
    // changing interface to pass in files would prevent customlocators from specifying files
  }
}
````

The project is available after Ioc is initialisated, How best to make the project instance available to the Default view locator without changing the Find() method signature?

**Comment by kevinkuszyk** [comment]
Good work with the `IServiceProvider`.  We should post a question in the [aspnet](https://github.com/aspnet/home) repro to find out if this is how they designed it to be used.

Regarding the `IViewLocator.Find()` signature, what are you thoughts on passing the project in?  So the signature would change to this:

````
View[] Find(Project project)
````

Also, do you have a strong preference for returning `View[]` vs `IEnumerable<View>`?

**Comment by wwwlicious** [comment]
No real preference on returning an array. What are you thoughts on picking one over the other?

the issue with passing the project into the find method, is it then requires custom implementations to deal with and reference the Project type. It seems cleaner to allow the custom implementations to implement a simple Find() method where they can just create an array to View instances.

For the time being I've put a Func<Project> delegate into the defaultrazorviewlocator and I add this to the default view locator (which I hold as private field in the compilermode) once the project object is available. It still allows the hostapp to clear the viewlocators and Ioc still works as I register the collections as an instance,

**Comment by kevinkuszyk** [comment]
Re. return types - I usually go with the lowest interface I can.

I don't have problem with custom locators having to take a dependency on the framework so they can use the `Project` and other types.  I'm more concerned with using a `Func` to pass objects into the locator because the method doesn't have the required args.

If you feel strongly that we shouldn't have the `Project` on the interface, how about changing the method signature to:

````
IEnumerable<View> Find(string projectDirectory) 
````

**Comment by wwwlicious** [comment]
If you want to change this to pass an argument then I think using the directoryPath is probably a good call.

**Comment by kevinkuszyk** [comment]
Ok, let's go with with passing the project directory in.  If the implementation starts to get difficult because we don't have access to the `Project` we should reconsider. 

> As an end user of lots of other packages myself, it's always preferrable that they not bring the kitchen sink and the occasional versioning hassles with them so I'm concious to try and limit them as much as possible.

Yes, I'm all for keeping it as simple as possible!

**Comment by artiomchi** [comment]
This is pretty old not, and I don't think it's relevant at this point, so I'm closing it

**Pull request closed without merging**
