### PR TITLE
Checkpoint merge, working modules, potential alpha stage

### PR DESCRIPTION
**Pull request by artiomchi**
Large set of changes since the previous stage.. Large parts of the code have been reworked, but it's far from a complete work. So far a lot of the functionality is in place and working. I've tested it in limited scenarios, and it worked, but I'd need more testing in various projects/circumstances to get more use cases, and see how it's faring so far.

The code is far from perfect. In the end, since building code using the SyntaxFactory is complex, I decided to work on the project in multiple stages.

1. Get the basic functionality in place, and start using the project to get some mileage / live testing
2. Add unit tests to cover the functionality, make sure we have an expected behaviour baseline
3. Deep core refactoring, cleaning up, optimisation and abstraction. Use the unit tests to make sure the behaviour isn't changed in the process.

This pull request is a large part of stage 1.

Working so far:
- Library project multi targeting, will work on both .NET Core projects and .NET Framework ones
- Tools library (code generation) successfully generates the helpers. Can be triggered using the powershell Package Manager Console in VS. Technically can be triggered outside of VS as well, but currently it's Windows only (MSBuild limitation)
- Generator configuration (r4mvc.json file can be placed in the root of the project)
- Updating existing controllers to make them partial, change methods to be virtual
- Generating R4Mvc_[…] classes with method overrides, handling parameters (only basic serialisation)
- Creates MVC.[…] helpers that use the avove
- MVC class also exposes controller views, including views without controllers (e.g. Shared views folder)
- Support for areas is in! (both using the `AreaAttribute` and directly derived attribute classes (using syntax tree analysis, only digging one level deep. If using derived attributes, they have to be part of the web project)
- `IHtmlHelper` and `UrlHelper` extensions for link and url generation, as well as form action tag population
- Tag helper support also present
- Ability to create generated controller files as part of R4Mvc.cs or nested under their respective controller classes (the new project files have auto-nesting based on file names. So this ended up the logical step to make, plus I personally prefer it. Generating all controller files in the root of the project caused them not to nest at all)

Known issues:
- Area clash detection is currently trivial. Will append "Area" to area names if there's a root controller with the same name. Work in progress to make it reliable
- When updating the generator, VS will have to be restarted for the new version of the tool to be used. The tool project will have to be "wrapped" in a invoker assembly for nuget bundling (affects both PowerShell and (future) cli approach). I have a solution, but it's work in progress
- Depending on how a controller is deleted, it's generated.cs file might not be cleaned up by the generator automatically. Yet :)

### CODE REVIEW

**Comment by artiomchi** [comment]
Issues affected by this pull request:
- #2: Dependency injection is in place, and is working great! **done**
- #7 Generate partial controller classes: **done**
- #8 Generate derived controller classes: **done**
- #9 Generate helper methods on generated partial controllers: **done**
- #10 Generate overridden action methods on generated derived controllers: **done**
- #11 Generate view name constants in generated partial controllers: **done** using readonly strings, same as T4MVC
- #12 Generate action name constants in generated partial controllers: **done** using readonly strings and constancs, same as T4MVC
- #14

**Comment by artiomchi** [comment]
A small note regarding this pull request, before we make it "public" with an alpha.

The original c# project was named `R4Mvc` (with this casing), so I kept it consistent across the project. It also keeps it consistent with how Microsoft named their classes (e.g. `Microsoft.AspNetCore`). At first I thought to make it uppercase, similar to T4MVC, but I switched back to R4Mvc. When you make it public, I think it makes sense to do the same.

**Comment by artiomchi** [comment]
I saw you started a app-veyor branch with the build and pack configuration, and wanted to give some feedback on that as well. You used nuget and msbuild for the restore and pack operations, but starting with .net core this process was simplified and can be achieved using the dotnet cli. AppVeyor can build the projects using their build step, but you can't pass parameters to msbuild directly, so I used a build script. It also makes it more consistent and easy to read.

Most of the NuGet package information is picked up from the .csproj  file, including the project URL, authors, description and version. I used a version prefix to allow AppVeyor to append the build number for CI builds.

**Comment by artiomchi** [comment]
Other available parameters can be seen on this docs page: https://docs.microsoft.com/en-us/dotnet/core/tools/csproj in the "NuGet metadata properties" section

**Comment by artiomchi** [comment]
I've changed the  build version from `0.6.0-ci-16` to `0.6.0-ci.16` to conform with SemVer 2.0. It's incompatible with older versions of NuGet, but that doesn't matter, since developers writing for .NET core will have to use newer versions of NuGet anyway. The benefit on SemVer 2.0 is that build numbers will be ordered correctly.

So `0.6.0-ci-16` < `0.6.0-ci-2` but`0.6.0-ci.16` > `0.6.0-ci.2`

**Comment by kevinkuszyk** [comment]
@artiomchi wow!  Thanks there is a lot here.  I've scanned through and it all looks good to me.

The `appveyor.yml` that I have in the other branch is very much a work in progress still.  I'll merge this and then spend some more time on it tonight.

**Pull request merged**
