### PR TITLE
Suggesting a new build script

### PR DESCRIPTION
**Pull request by artiomchi**
Hey @kevinkuszyk 

Seeing as you were quite busy, and trying to move things a bit forward, I thought to play around with the build script. Here's what I came up with to help move #49 along (a sort of alternative to #48)

Here's what the new build script provides:
- Better versioning. As much as I live SemVer 2.0, I decided to go back to 1.0, and use dash based versions numbers. To make sure they're ordered correctly, the build numbers will be padded to 5 digits (sort of what MS does with their build numbers)
- The main version number will be stored in a single property in the project (`VersionPrefix`). It has to be number based (i.e. Major.Minor.Patch), so that it's also used in the assembly and file version automatically. Final releases will use this field for the package version number. Any other branches (CI, alpha, beta, etc) will populate the version suffix, making them pre-release builds.
- Following Git Flow, the `master` branch will be used for final releases. Pushes to the master branch will not use the version suffix (e.g. version `1.0.1`), and will deploy successful builds to NuGet
- The `develop` branch will be the main dev branch in the project, replacing the current master one. Builds to this branch will get a ci version suffix (e.g. version `1.0.1-ci-00137`), and will be pushed to the MyGet for the latest bleeding edge builds
- There'a a simple way to deploy pre-release builds to the global NuGet repository - just use release path branches. For example, pushing to `release\alpha1` will get a alpha1 version suffix (e.g. version `1.0.1-alpha1-00137`) and will be pushed to the public NuGet repo

Main benefits to this is that we'll bump the version of the code after each major release. At which point new CI builds will automatically be for the next version, same once they get to alpha/beta stages. And once we're ready to go live, we just push to master, and it goes live.

MyGet will be used only for CI builds, while alpha/beta and final releases will be pushed to the main NuGet repo. 

If you think it's worth approving, I suggest we merge into the develop branch, rather than the master one (don't want to prematurely push a release build). 
You'd also have to populate the right API keys for MyGet and NuGet, and set the repository URL for MyGet.

We can populate the package descriptions and everything else in the csproj files.

Thoughts?

### CODE REVIEW

**Comment by artiomchi** [comment]
P.S. The script will run any other branches as well (for pull request builds, for example), but only the specified branches above will have their artifacts deployed

**Comment by kevinkuszyk** [comment]
@artiomchi sounds good.  I was thinking more along the lines of:

1. Every build gets pushed to MyGet.
2. Builds from all branches get a pre release `-ci` suffix.
3. Builds from tags on `master` get pushed to NuGet.

> Seeing as you were quite busy, and trying to move things a bit forward

Yes, I've been thinking about this.  I'm acutely aware you have much more time for R4MVC than I do at them moment, and I'm holding you back.  How about I give you push access to the repro?

**Comment by artiomchi** [comment]
@kevinkuszyk Hmm.. If I understood you correctly, the only difference between your 3 points and this pull request are:

- [+] This PR adds custom tag pre-releases based on release branches (i.e. alpha/beta branching)
- [-] The code in PR only pushes the develop branch commits to MyGet

When playing with this, I've initially done the same thing (push all commits to CI), at which point I realised that the CI builds will be a complete mess.

Say there's active development done in the dev branch, and someone creates a feature branch to test something. With active commits in both branches, you'll never know whether a CI build on MyGet is from the main dev branch or from a feature branch which may have breaking changes. Any user following CI builds on MyGet is bound to be frustrated at this point.

I'm not 100% sure, but I think that could cause third party PR builds to also be pushed to CI :)

If you want branch builds to be pushed to MyGet as well, we can add another deploy rule to push all `feature/*` branches to MyGet as well, with a `-ci-[featurename]` suffix, similar to release ones. What do you think?

P.S. Sure, I'm perfectly happy to push commits directly here, instead of my fork. I'll do my best to support the project to the best of my ability, and will keep consulting with you and @davidebbo (and the community) on feature decisions and other larger changes :)

**Comment by artiomchi** [comment]
Small patch based on the above discussion will also push feature branches to ci in MyGet. So a feature branch called `feature/aspnetcore-2` will be pushed to ci as `0.6.0-ci-aspnetcore-2-00139`

Thanks to the sorting algorithm for SemVer 1, the regular CI builds will be considered "newer", so anyone that's updating to CI builds won't accidentally get a feature branch build. At the same time, anyone that wants to follow a feature branch ci build, can just install the latest builds with that suffix. So one could specify `0.6.0-ci-aspnetcore-2-*` as a version number to get the latest CI builds in that branch (according to the [docs](https://docs.microsoft.com/en-us/nuget/create-packages/dependency-versions#version-ranges), at least)

I also changed the prefix for pre-release builds to follow the `prerelease\*` branches rather than `release\*` ones to not break GotFlow patterns

**Comment by kevinkuszyk** [comment]
> Say there's active development done in the dev branch, and someone creates a feature branch to test something. With active commits in both branches, you'll never know whether a CI build on MyGet is from the main dev branch or from a feature branch which may have breaking changes. Any user following CI builds on MyGet is bound to be frustrated at this point.

Good point.  I hadn't considered that.

You should have an invite to join this org in your inbox.  Once you accept that you should have write access to this repo.

Feel free to @ mention me if you need a hand with anything.  Over to you now....

**Comment by artiomchi** [comment]
@kevinkuszyk Looks good so far. 

One last thing before I merge this PR.. You already have a T4MVC AppVeyor account that has a webhook tied to this repo. I'm not sure if you already have a T4MVC MyGet account that will host the CI builds.

Could you set one up, and update the appveyor.yml with the correct MyGet repo url as well as the encoded api key for MyGet. Don't forget to do it in the `develop` branch, by the way.

We can do the same for the NuGet api key (no need for the server address there) so that we can also start publishing alpha builds

**Pull request merged**
