### PR TITLE
syncing up dev branch with changes so far

### PR DESCRIPTION
**Pull request by wwwlicious**
changes include 

the first part of the ControllerRewriter for modifying classes to partial covering #6 
writing the generated file to the project root folder #5 using the project object in ICompileContext
Generating file with the project root namespace #4 
Generating partial controller classes #7 

all feedback welcome :)

### CODE REVIEW

**Comment by kevinkuszyk** [comment]
Wow!  You've had a busy weekend!

Is this ready to merge?  If so I try to review and merge tonight.

**Comment by wwwlicious** [comment]
yes, its ready to merge, with the caveat that there aren't any unit tests and the old adage 'works on my machine!' :)

**Comment by kevinkuszyk** [comment]
Thanks - it's really starting to come together now.

We need to sort the unit tests, but they can wait for now until we figure out how to decouple it all.

We also need to standardize on some coding standards for naming, casing etc.  I was thinking we should follow the same [guidelines](https://github.com/aspnet/Home/wiki/Engineering-guidelines#coding-guidelines) as the asp.net team.  Thoughts?

Before we start refactoring let's get the unit tests in, so we can make sure we don't regress any functionality.  I'll spend some time trying to get framework figured out.

You should be able to pull the latest into your `master` branch now and delete your `dev` branch.  If you can work in topic branches now and open pull requests hopefully we can get the GitHub flow working.

**Comment by wwwlicious** [comment]
the guidelines look good so agree, let go with that. Would help though if you could keep me right on any I miss, engrained habits and all that, plus VS is always messing about with tabs and spacing in project files :)

I have no probs with creating unit tests but I can't get this working locally so would rather concentrate on getting the basic functionality/skelton built out. Once you figure out what's stopping the appveyor running the tests at least we can run them in the console. Might be waiting a while for VS runner to catch up though.

dev branch has been deleted, will try to keep to the correct flow, as long as I have like 3 git commands to run I'm good, venturing further than that is just scary for me! ;)

**Pull request merged**
